name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-trailing:
    runs-on: self-hosted
    steps:
      - name: Lint Trailing Whitespace
        uses: cb0n3y/ci-templates/.github/workflows/lint-trailing.yml@main
