name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-trailing:
    name: Lint Trailing Whitespace
    uses: cb0n3y/ci-templates/.github/workflows/lint-trailing.yml@main
